# Conference info
conf:
  name: Conferencia do Keppelen =]
  description: A melhor conferencia do planeta
  date: october 12
  price: $500
  address: Av. presidente vargas, 1001, rio de janeiro
  venue: Coco Bongo
  city: Brazil

# Site info
url: http://confboilerplate.com
favicon: http://braziljs.org/favicon.ico
google-analytics: UA-33656081-1
images:
  cover: http://4.bp.blogspot.com/-mr-Arm6LZik/Tys0s7yUP7I/AAAAAAAADfU/lRFze1I8uWo/s1600/aaaaaaest.jpg
  facebook: http://braziljs.org/img/fb-share.jpg

# Active sections on the website
sections:
  about: true
  location: true
  speakers: true
  schedule: true
  sponsors: true
  partners: false
  contact: false

# The entire schedule
schedule:
  - name: Check-in / Breakfast
    time: 9h00

  - name: Giovanni Keppelen
    photo: http://braziljs.org/img/avatar/giovanni.jpg
    bio: Fundador do Front in BH e moderador do Rio.js. Estudante de Produção Multimídia Production na UNI-BH. Front-end Engineer e Tech Leader no Peixe Urbano, sempre focando em performance
    company: Peixe Urbano
    twitter: keppelen
    presentation:
      title: title Palestra
      description: description da palestra
      time: 10h00

  - name: Bill Gates
    photo: http://f.cl.ly/items/2A3p1N0C3c0n3N3R1w2B/speaker.jpg
    bio: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    company: Microsoft
    twitter: billy95
    presentation:
      title: Introducing Windows 12
      description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      time: 11h00

  - name: Lunch
    time: 12h00

  - name: Chuck Norris
    photo: http://f.cl.ly/items/2A3p1N0C3c0n3N3R1w2B/speaker.jpg
    bio: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    company: Delta Command
    twitter: littlechuck
    presentation:
      title: How to kill a elephant with one finger
      description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      time: 13h00

  - name: Steve Jobs
    photo: http://f.cl.ly/items/2A3p1N0C3c0n3N3R1w2B/speaker.jpg
    bio: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    company: Apple, Inc.
    twitter: stevie
    presentation:
      title: Presenting iPad
      description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      time: 14h00

  - name: Coffee-break
    time: 15h00

  - name: Mark Zuckerberg
    photo: http://f.cl.ly/items/2A3p1N0C3c0n3N3R1w2B/speaker.jpg
    bio: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    company: Facebook
    twitter: zuck
    presentation:
      title: Revealing Facebook Secrets
      description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      time: 16h00

  - name: Steve Wozniak
    photo: http://f.cl.ly/items/2A3p1N0C3c0n3N3R1w2B/speaker.jpg
    bio: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    company: Apple, Inc.
    twitter: woz
    presentation:
      title: Why do I prefer Android over iPhone
      description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      time: 17h00

# List of Sponsors
sponsors:
  - name: Eventick
    logo: http://f.cl.ly/items/1U3p0Z0e2w0I1i3z1X22/Image%202012.09.25%203:00:58%20PM.png
    url: http://eventick.com.br

  - name: Peixe Urbano
    logo: http://drieverywhere.net/wp-content/uploads/2010/04/peixe_urbano_logo.jpg
    url: http://peixeurbano.com.br

# List of Partners
partners:
  - name: BrazilJS
    logo: http://f.cl.ly/items/2N3i2W0X2f3c2g2Z2N0f/Untitled-1.png
    url: http://braziljs.org